services:
  database:
    container_name: starfish-database
    image: postgres:18.0-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=starfish_admin
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=starfish_database
    volumes:
      - database:/var/lib/postgresql/data
  
volumes:
  database:
    driver: local 