name: Build Docker Images

on:
  push:
    branches: ["main"]
    paths:
      - server/**
      - .github/workflows/build-docker-images.yml

  workflow_dispatch:

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      server: ${{ steps.filter.outputs.server }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Filter Modified Files
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            server:
              - 'server/**'
              - '.github/workflows/build-docker-images.yml'

  build:
    name: Build Docker Images
    needs: changes
    if: needs.changes.outputs.server == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: blacksmith-4vcpu-ubuntu-2404
    permissions:
      contents: read
      packages: write
    outputs:
      digest: ${{ steps.push.outputs.digest }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Docker Builder
        uses: useblacksmith/setup-docker-builder@v1

      - name: Login to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        id: push
        uses: useblacksmith/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/makestarfish/starfish:latest
          context: server

  release:
    name: Release
    needs: [changes, build]
    if: always() && (needs.build.result == 'success' || needs.build.result == 'skipped') && (needs.changes.outputs.server == 'true' || github.event_name == 'workflow_dispatch')
    uses: ./.github/workflows/release.yml
    with:
      starfish-digest: ${{ needs.build.outputs.digest }}
      starfish-render-service-id: "srv-d76kc49aae7s73c78q20"
    secrets:
      RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
